name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
    
    - name: Set up Java
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2  # v3
      with:
        distribution: temurin
        java-version: 21
        cache: sbt
    
    - name: Set up SBT
      uses: sbt/setup-sbt@d02b7c9920deb761624de4ec76249d9c76f00ca7  # v1
      
    - name: Compile and test
      run: sbt compile Test/compile test
